export const ar = {
  sidebar: {
    brand: 'ترانس إي آر بي',
    brandSub: 'النقل والسياحة',
    main: 'رئيسي',
    finance: 'المالية',
    system: 'النظام',
    dashboard: 'لوحة القيادة',
    fleet: 'الأسطول',
    legs: 'الساقين',
    operations: 'العمليات',
    expenses: 'المصروفات',
    accounting: 'المحاسبة',
    arAp: 'قبض / دفع',
    reports: 'التقارير',
    settings: 'الإعدادات',
    signOut: 'تسجيل خروج',
  },
  legs: {
    title: 'الساقين',
    driversTab: 'السائقين',
    licenseGradesTab: 'درجات الرخصة',
    addLicenseGrade: 'إضافة درجة',
    editLicenseGrade: 'تعديل درجة',
    licenseGradeName: 'الاسم',
    code: 'الكود',
    fullName: 'الاسم الكامل',
    phone: 'الهاتف',
    licenseGrade: 'درجة الرخصة',
    status: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    actions: 'الإجراءات',
    view: 'عرض',
    edit: 'تعديل',
    toggleConfirmTitle: 'تأكيد تغيير الحالة',
    toggleActivateMsg: 'هل أنت متأكد من تفعيل هذا الساق؟',
    toggleDeactivateMsg: 'هل أنت متأكد من إلغاء تفعيل هذا الساق؟',
    confirm: 'تأكيد',
    cancel: 'إلغاء',
    details: 'التفاصيل',
  },
  header: {
    search: 'بحث...',
  },
  fleet: {
    vehicles: 'المركبات',
    drivers: 'السائقين',
    types: 'أنواع المركبات',
    addVehicle: 'إضافة مركبة',
    addDriver: 'إضافة سائق',
    addType: 'إضافة نوع',
    toggleActive: 'تفعيل / إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    code: 'الكود',
    plate: 'اللوحة',
    model: 'الموديل',
    year: 'السنة',
    capacity: 'السعة',
    type: 'النوع',
    driver: 'السائق',
    status: 'الحالة',
    actions: 'الإجراءات',
    details: 'تفاصيل',
    codeLabel: 'الكود:',
    plateLabel: 'اللوحة:',
    yearLabel: 'السنة:',
    capacityLabel: 'السعة:',
    typeLabel: 'النوع:',
    driverLabel: 'السائق:',
    statusLabel: 'الحالة:',
    unassigned: 'غير معين',
    history: 'السجل',
    loading: 'جار التحميل...',
    noHistory: 'لا توجد سجلات سابقة',
    date: 'التاريخ',
    plateCol: 'اللوحة',
    active: 'نشط',
    fullName: 'الاسم الكامل',
    phone: 'الهاتف',
    nationalId: 'الرقم القومي',
    licenseGrade: 'درجة الرخصة',
    name: 'الاسم',
    modelCode: 'كود الموديل',
    capacityUnit: 'طن',
    toggleConfirmTitle: 'تأكيد تغيير الحالة',
    toggleActivateMsg: 'هل أنت متأكد من تفعيل هذه المركبة؟',
    toggleDeactivateMsg: 'هل أنت متأكد من إلغاء تفعيل هذه المركبة؟',
    confirm: 'تأكيد',
    cancel: 'إلغاء',
    chassisNumber: 'رقم الشاسية',
    engineNumber: 'رقم الماتور',
    gps: 'GPS',
    gpsFound: 'موجود',
    gpsNotFound: 'غير موجود',
    licenseDate: 'تاريخ الترخيص',
    licenseExpiry: 'انتهاء الترخيص',
    ownerName: 'اسم المالك',
    licenseTypeLabel: 'نوع الترخيص',
    purchaseDate: 'تاريخ الشراء',
    search: 'بحث بلوحة، كود، شاسية، أو ماتور',
    allModels: 'جميع الموديلات',
    allStatuses: 'جميع الحالات',
    inactive: 'غير نشط',
  },
  fleetModals: {
    addVehicle: 'إضافة مركبة',
    editVehicle: 'تعديل مركبة',
    addDriver: 'إضافة سائق',
    editDriver: 'تعديل سائق',
    addType: 'إضافة نوع مركبة',
    editType: 'تعديل نوع مركبة',
    code: 'الكود',
    plateNumber: 'رقم اللوحة',
    model: 'الموديل',
    year: 'السنة',
    capacity: 'السعة',
    type: 'النوع',
    assignDriver: 'تعيين سائق (اختياري)',
    noDriver: '— بدون سائق —',
    fullName: 'الاسم الكامل',
    phone: 'الهاتف',
    nationalId: 'الرقم القومي',
    licenseGrade: 'درجة الرخصة',
    insuranceNumber: 'رقم التأمين',
    salary: 'الراتب',
    hireDate: 'تاريخ التعيين',
    name: 'الاسم',
    modelCode: 'كود الموديل',
    save: 'حفظ التغييرات',
    cancel: 'إلغاء',
    add: 'إضافة',
    selectType: '— اختر النوع —',
    selectDriver: '— بدون سائق —',
    chassisNumber: 'رقم الشاسية',
    engineNumber: 'رقم الماتور',
    gps: 'GPS',
    licenseDate: 'تاريخ الترخيص',
    licenseExpiry: 'تاريخ انتهاء الترخيص',
    ownerName: 'اسم المالك',
    licenseType: 'نوع الترخيص',
    purchaseDate: 'تاريخ الشراء',
  },
  dashboard: {
    revenue: 'الإيرادات (الشهر)',
    activeTrips: 'الرحلات النشطة',
    expenses: 'المصروفات (الشهر)',
    netProfit: 'صافي الربح (الشهر)',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    margin: 'هامش الربح',
    revenueVsExpenses: 'الإيرادات vs المصروفات',
    fleetStatus: 'حالة الأسطول',
    recentTrips: 'آخر الرحلات',
    outstandingInvoices: 'الفواتير المستحقة',
    active: 'نشط',
    maintenance: 'صيانة',
    inactive: 'غير نشط',
    driversAvailable: 'السائقون المتاحون',
    revenueChart: 'الإيرادات',
    expensesChart: 'المصروفات',
    profitChart: 'الأرباح',
    route: 'المسار',
    customer: 'العميل',
    amount: 'المبلغ',
    status: 'الحالة',
    invoice: 'الفاتورة',
    due: 'تاريخ الاستحقاق',
    balance: 'الرصيد',
    inProgress: 'قيد التنفيذ',
    pending: 'معلق',
  },
  trips: {
    allStatuses: 'جميع الحالات',
    pending: 'معلق',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    cancelled: 'ملغي',
    newTrip: 'رحلة جديدة',
    orderWorkflow: 'سير العمل',
    id: 'المعرف',
    route: 'المسار',
    customer: 'العميل',
    vehicle: 'المركبة',
    date: 'التاريخ',
    salePrice: 'سعر البيع',
    status: 'الحالة',
    actions: 'الإجراءات',
    start: 'بدء',
    cancel: 'إلغاء',
    complete: 'إكمال',
  },
  expenses: {
    vehicleExpenses: 'مصروفات المركبات',
    tripExpenses: 'مصروفات الرحلات',
    currencies: 'العملات',
    recordExpense: 'تسجيل مصروف',
    expenseBreakdown: 'تحليل المصروفات',
    monthlyTrend: 'الاتجاه الشهري',
    vehicle: 'المركبة',
    type: 'النوع',
    date: 'التاريخ',
    amount: 'المبلغ',
    payment: 'الدفع',
    notes: 'ملاحظات',
    selectTrip: 'اختر رحلة لعرض مصروفاتها',
    code: 'الكود',
    name: 'الاسم',
    rate: 'السعر (للأساس)',
    baseCurrency: 'العملة الأساسية',
  },
  accounting: {
    chartOfAccounts: 'دليل الحسابات',
    journalEntries: 'قيود اليومية',
    fiscalPeriods: 'الفترات المالية',
    costCenters: 'مراكز التكلفة',
    newAccount: 'حساب جديد',
    manualEntry: 'قيد يدوي',
    reverse: 'عكس',
    close: 'إغلاق',
    allSources: 'جميع المصادر',
    manual: 'يدوي',
    tripCompleted: 'رحلة مكتملة',
    paymentReceived: 'تم التحصيل',
    expenseRecorded: 'تم التسجيل',
    reversal: 'عكس',
    number: 'الرقم',
    date: 'التاريخ',
    description: 'الوصف',
    source: 'المصدر',
    debit: 'مدين',
    credit: 'دائن',
    status: 'الحالة',
    actions: 'الإجراءات',
    period: 'الفترة',
    type: 'النوع',
    start: 'البداية',
    end: 'النهاية',
    closed: 'مغلق',
    open: 'مفتوح',
    name: 'الاسم',
  },
  arAp: {
    customerInvoices: 'فواتير العملاء',
    customerPayments: 'مدفوعات العملاء',
    supplierInvoices: 'فواتير الموردين',
    supplierPayments: 'مدفوعات الموردين',
    invoiceNo: 'رقم الفاتورة',
    customer: 'العميل',
    date: 'التاريخ',
    dueDate: 'تاريخ الاستحقاق',
    total: 'الإجمالي',
    paid: 'المدفوع',
    status: 'الحالة',
    supplier: 'المورد',
    noRecords: 'لا توجد سجلات',
  },
  reports: {
    trialBalance: 'ميزان المراجعة',
    incomeStatement: 'قائمة الدخل',
    balanceSheet: 'الميزانية العمومية',
    balanced: 'متوازن',
    account: 'الحساب',
    debit: 'مدين',
    credit: 'دائن',
    balance: 'الرصيد',
    total: 'الإجمالي',
    totalRevenue: 'إجمالي الإيرادات',
    totalExpenses: 'إجمالي المصروفات',
    netProfit: 'صافي الربح',
    assets: 'الأصول',
    liabilitiesAndEquity: 'الخصوم وحقوق الملكية',
    totalAssets: 'إجمالي الأصول',
    totalLiabilities: 'إجمالي الخصوم',
    totalEquity: 'إجمالي حقوق الملكية',
    totalLE: 'إجمالي الخصوم وحقوق الملكية',
  },
  settings: {
    users: 'المستخدمون',
    outbox: 'الرسائل الصادرة',
    auditLog: 'سجل التدقيق',
    createUser: 'إنشاء مستخدم',
    changeRole: 'تغيير الدور',
    deactivate: 'إلغاء التنشيط',
    code: 'الكود',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    role: 'الدور',
    lastLogin: 'آخر دخول',
    status: 'الحالة',
    never: 'أبداً',
    id: 'المعرف',
    eventType: 'نوع الحدث',
    retries: 'عدد المحاولات',
    occurred: 'التاريخ',
    error: 'الخطأ',
    timestamp: 'الوقت',
    user: 'المستخدم',
    table: 'الجدول',
    action: 'الإجراء',
    details: 'التفاصيل',
  },
  statusBadge: {
    active: 'نشط',
    inactive: 'غير نشط',
    maintenance: 'صيانة',
    pending: 'معلق',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    cancelled: 'ملغي',
    draft: 'مسودة',
    posted: 'مرسل',
    partiallyPaid: 'مدفوع جزئياً',
    paid: 'مدفوع',
    processed: 'تمت المعالجة',
    failed: 'فشل',
    employee: 'موظف',
    contractor: 'مقاول',
    admin: 'مدير',
    accountant: 'محاسب',
    operator: 'مشغل',
    viewer: 'مشاهد',
    manual: 'يدوي',
    tripCompleted: 'رحلة مكتملة',
    paymentReceived: 'تم التحصيل',
    expenseRecorded: 'تم التسجيل',
    reversal: 'عكس',
  },
  modals: {
    newOrder: 'أمر تشغيل جديد',
    recordExpense: 'تسجيل مصروف مركبة',
    manualJournal: 'قيد يومية يدوي',
    newAccount: 'حساب جديد',
    createUser: 'إنشاء مستخدم',
    customer: 'العميل',
    tripDate: 'تاريخ الرحلة',
    from: 'من',
    to: 'إلى',
    salePrice: 'سعر البيع',
    currency: 'العملة',
    exchangeRate: 'سعر الصرف',
    entryDate: 'تاريخ القيد',
    fiscalPeriod: 'الفترة المالية',
    description: 'الوصف',
    lines: 'البنود',
    normalBalance: 'الرصيد الطبيعي',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    role: 'الدور',
    expenseType: 'نوع المصروف',
    paymentMethod: 'طريقة الدفع',
    amount: 'المبلغ',
    date: 'التاريخ',
    notes: 'ملاحظات',
    vehicle: 'المركبة',
    addLine: '+ إضافة بند',
    remove: 'إزالة',
    balance: 'الرصيد:',
    balanced: 'متوازن',
    unbalanced: 'غير متوازن',
    postEntry: 'ترحيل القيد',
    createAccount: 'إنشاء حساب',
    createOrder: 'إنشاء أمر',
    save: 'حفظ التغييرات',
    cancel: 'إلغاء',
    type: 'النوع',
    code: 'الكود',
    selectCustomer: '— اختر العميل —',
    selectVehicle: '— اختر المركبة —',
    fuel: 'وقود',
    maintenance: 'صيانة',
    tires: 'إطارات',
    oil: 'زيت',
    tolls: 'رسوم مرور',
    otherExpense: 'أخرى',
    cash: 'نقداً',
    bank: 'بنك',
    asset: 'أصل',
    liability: 'التزام',
    equity: 'حق ملكية',
    revenue: 'إيراد',
    expense: 'مصروف',
    debit: 'مدين',
    credit: 'دائن',
    create: 'إنشاء',
  },
}
